---
title: "Exercise 1"
author: "Rockefeller University, Bioinformatics Resource Centre"
date: "https://rockefelleruniversity.github.io/Intro_To_Python/"
output: 
  html_document:
    number_sections: false  ## if you want number sections at each table header
    theme: united  # many options for theme, this one is my favorite.
    highlight: tango  # specifies the syntax highlighting style
params:
  toMessage: false    
---

```{r, setup,include=FALSE}
toMessage <- ifelse(!is.null(params$toMessage), params$toMessage, FALSE)
message(toMessage)
```


<p>&nbsp;</p>
These exercises are about data types from Session 1 [session1](https://rockefelleruniversity.github.io/Intro_To_Python/). 


**Exercise 1** - **Lists**

- Create a list containing the values 1,2,3,4,5.

```{python,echo=toMessage}
[1,2,3,4,5]

```
- Create a list containing the values a,b,c,d,e, but assign it to a new variable called `x`.

```{python,echo=toMessage}
x = ["a","b","c","d","e"]
x
```

- Create a list containing the values a,b,c, repeated 5 times and assign it to a new variable

```{python,echo=toMessage}
y = ["a","b","c"] * 5
y
```

- Create a sublist with indexing. Use the variable you just created and extract the the 10th through to 14th position.

```{python, echo=toMessage}
y[9:14]
```

- With the same variable, let's use "-" indexing to get the last value of our list.
    
```{python, echo=toMessage}

y[-1]


```

- Now print the values from [0:-1]
    
```{python, echo=toMessage}

y[0:-1]


```

- Notice how the last value of your list is missing, even though you access it with [-1]. That's because slicing is exclusive, while indexing is inclusive. 
    

- Append the list in variable x. Add the string z.
```{python, echo=toMessage}
x.append('z')
x
```

- Delete the 2nd through 6th entry of x.
```{python, echo=toMessage}
del(x[1:5])
x
```

- Lets go back to variable y. Sort it in reverse order.
```{python, echo=toMessage}
y.sort(reverse=True)
y
```

  
- Multiply the y variable by 2. 
    
```{python, echo=toMessage}

y * 2



```
    

- Use the function .remove() to eliminate "a" from your list.
    
```{python, echo=toMessage}

y.remove("a")

print(y)

```

- Notice that .remove() eliminates only the first instance of your specified entry.
   
- Create a list of lists. Use the values 1,2,3,4,5, along with the lists x and y. 

```{python, echo=toMessage}
nested_list = [[1,2,3,4,5], x, y]
nested_list
```

- Take your previous list of lists and use indexing to find the third entry of your third list.

```{python, echo=toMessage}

nested_list[2][2]

```

**Exercise 2** - **Tuples**

- Create a tuple containing the values 1,2,3,4,5.

```{python,echo=toMessage}
(1,2,3,4,5)

```


- Coerce list in variable x into a tuple.

```{python,echo=toMessage}
tuple(x)

```


- Make a touple with your list of lists.
- Print your results
    
```{python, echo=toMessage}

nested_list_tuple = tuple(nested_list)

print(nested_list_tuple)

```

**Exercise 3** - **Dictionaries**

- Create a dictionary containing a list of floats, a list of integers and a tuple of strings.

```{python,echo=toMessage}

my_dict = {
    'my_float_list': [1.5,2.5,3.5],
    'my_integer_list': [4,5,6],
    'my_strings_tuple': ("a","b","c")
}
my_dict

```

- Create a dictionary containing GO terms and their corresponding genes:
    - GO:0030955 - PKM, ADPRH, ATP4A, DRG1
    - GO:0031403 - IMPA1, PDXK
    - GO:0031402 - SLC6A4, CAPN3, TDG, ATP1A2

```{python,echo=toMessage}

my_dict = {
    'GO:0030955': ["PKM", "ADPRH", "ATP4A", "DRG1"],
    'GO:0031403': ["IMPA1", "PDXK"],
    'GO:0031402': ["SLC6A4", "CAPN3", "TDG", "ATP1A2"]
}
my_dict

```

- Add a new parental GO term: GO:0031420. This contains all the genes from the other 3 entries.  

```{python,echo=toMessage}

my_dict = {
    'GO:0030955': ["PKM", "ADPRH", "ATP4A", "DRG1"],
    'GO:0031403': ["IMPA1", "PDXK"],
    'GO:0031402': ["SLC6A4", "CAPN3", "TDG", "ATP1A2"]
}
my_dict.setdefault('GO:0031420', my_dict['GO:0030955'] + my_dict['GO:0031403'] + my_dict['GO:0031402'])
my_dict
```

- Make a new version of the original gene ontolgoy dictionary, but add the names of each term to each entry, in addition to the genes. The following information should be accessible in the object:

Hint: Dictionary elements can also be nested dictionaries.

- GO:0030955
  + Name: potassium ion binding
  + Genes: PKM, ADPRH, ATP4A, DRG1
- GO:0031403
  + Name: lithium ion binding
  + Genes: IMPA1, PDXK
- GO:0031402 
  + Name: sodium ion binding
  + Genes: SLC6A4, CAPN3, TDG, ATP1A2

```{python, echo=toMessage} 
my_dict_names = {
    'GO:0030955': {"name": "potassium ion binding",
                   "genes": ["PKM", "ADPRH", "ATP4A", "DRG1"]},
    'GO:0031403': {"name": "lithium ion binding",
                   "genes": ["IMPA1", "PDXK"]},
    'GO:0031402': {"name": "lithium ion binding",
                   "genes": ["SLC6A4", "CAPN3", "TDG", "ATP1A2"]}
}
my_dict_names
```

- Index the object you made to separately get the name and genes for the term 'GO:0031403'.

```{python, echo=toMessage} 
# name 
my_dict_names["GO:0031403"]["name"]

# genes
my_dict_names["GO:0031403"]["genes"]
```


**Exercise 4** - **Sets**

- Create 2 sets of gene names: 
  - PKM, ADPRH, ZNF724,ATP4A,GSS, DRG1, FA2H, MCM10
  - SLC6A4, MCM10, CAPN3, TDG, ATP1A2,GSS, BRCA1, HIVEP2, PKM

```{python,echo=toMessage}

my_set1 = {"PKM", "ADPRH", "ZNF724","ATP4A","GSS", "DRG1", "FA2H", "MCM10"}
my_set2 = {"SLC6A4", "MCM10", "CAPN3", "TDG", "ATP1A2","GSS", "BRCA1", "HIVEP2", "PKM"}

```

- These are genes of interest from two experiments. What genes overlap between the two?

```{python,echo=toMessage}

my_set1.intersection(my_set2) 

```


