---
title: "Exercise 3"
author: "Rockefeller University, Bioinformatics Resource Centre"
date: "https://rockefelleruniversity.github.io/Intro_To_Python/"
output: 
  html_document:
    number_sections: false  ## if you want number sections at each table header
    theme: united  # many options for theme, this one is my favorite.
    highlight: tango  # specifies the syntax highlighting style
params:
  toMessage: false    
---

```{r, setup,include=FALSE}
toMessage <- ifelse(!is.null(params$toMessage), params$toMessage, FALSE)
message(toMessage)
```


<p>&nbsp;</p>
These exercises are about data types and custom functions from Session 1 [session1](https://rockefelleruniversity.github.io/Intro_To_Python/). 



**Exercise 1** - **NumPy**

- Import NumPy

```{python,echo=toMessage}

import numpy as np

```

 -  Create a NumPy array with the following 4 columns and 5 rows.

    - Sample - R1, R2, R3, R4, R5
    - Year - 1990, 2010, 2005, 2015, 2012
    - Replicate - True, True, False, False, False
    - Tissue - Skin, Skin, Brain, Brain, Brain

```{python,echo=toMessage}

arr_2d = np.array([["R1", 1990, True, "Skin"],
  ["R2", 2010, True, "Skin"], 
  ["R3", 2005, False, "Brain"],
  ["R4", 2015, False, "Brain"],
  ["R5", 2012, False, "Brain"]])
arr_2d

```

- Slice the array to get just the Sample and Year.

```{python,echo=toMessage}

arr_2d[:,0:2]

```

- Subset the array to just Brain Tissue samples. 

```{python,echo=toMessage}

arr_2d[arr_2d[:,3] =="Brain",:]

```

**Exercise 2** - **NumPy**

- Make an array that is 3 rows and 6 columns, and contains the numbers 1 through 18

```{python, echo=toMessage} 
# option 1
arr_num = np.array([[1,2,3,4,5,6],
                    [7,8,9,10, 11,12],
                    [13,14,15,16,17,18]])

# option 2 with reshape
arr_num = np.array([range(1,19)])
arr_num = arr_num.reshape(3,6)

arr_num
```

- Confirm that your array has the correct shape

```{python, echo=toMessage} 
arr_num.shape
```

- Modify the array so that it has 6 rows and 3 columns

```{python, echo=toMessage} 
arr_num_6x3 = arr_num.reshape(6,3)
```

- Index this array into two different arrays, one that contains the values less than 10, and another that contains values that are 10 or higher.

```{python, echo=toMessage} 
small_nums = arr_num_6x3[arr_num_6x3 < 10]
small_nums
big_nums = arr_num_6x3[arr_num_6x3 > 9]
big_nums
```

- Confirm the shape and dimensions of these arrays. 

```{python, echo=toMessage} 

small_nums.shape
small_nums.ndim
big_nums.shape
big_nums.ndim
```

- Convert both of the new arrays to two dimensional, 3 by 3 arrays.

```{python, echo=toMessage} 

small_nums_3x3 = small_nums.reshape(3,3)
small_nums_3x3
big_nums_3x3 = big_nums.reshape(3,3)
big_nums_3x3
```

- Concatenate these two arrays, joining them by columns.

```{python, echo=toMessage} 
arr_cat = np.concatenate((small_nums_3x3, big_nums_3x3), axis = 1)
arr_cat
```

**Exercise 3** - **Custom Functions**

- Create a function which takes one number and returns the square of that number

```{python,echo=toMessage}

def squareOfNumber(number):
  squareNumber = number*number
  return squareNumber

squareOfNumber(9)

```

- Create a function which takes two numbers and returns the mean and the minimum

```{python,echo=toMessage}

def mean_and_minOfNumbers(number1, number2):
  meanNumber = (number1 + number2) /2
  minNumber = min([number1, number2])
  return [meanNumber,minNumber]

mean_and_minOfNumbers(1,3)
```


- Edit the previous function to print a statement that telling us what the product of our number is. 

```{python,echo=toMessage}

def mean_and_minOfNumbers(number1, number2):
  meanNumber = (number1 + number2) /2
  minNumber = min([number1, number2])
  print("The product is " + str(number1*number2))
  return [meanNumber,minNumber]

mean_and_minOfNumbers(1,3)

```

- Add some default values to our function. Run the function without giving any arguments. 

```{python,echo=toMessage}

def mean_and_minOfNumbers(number1=10, number2=40):
  meanNumber = (number1 + number2) /2
  minNumber = min([number1, number2])
  print("The product is " + str(number1*number2))
  return [meanNumber,minNumber]

mean_and_minOfNumbers()

```

**Exercise 4** - **Custom Functions**

- Create function that takes three lists and coerces them into one set. The function must return the set, but also print its length.

** Think about each individual step required to do this**

```{python,echo=toMessage}

def SetMaker(list1, list2, list3):
  biglist = list1 + list2 + list3
  my_set = set(biglist)
  print(len(my_set))
  return my_set

```


Run the function using these inputs

```
list1 = ["INS","INSR", "VEGFA","VEGFR1","VEGFR2"]
list2 = ["TGFBR1","EGFR","VEGFR1","VEGFR2"]
list3 = ["APOE", "IL6", "TGFB1","TGFBR1","TNF"]

```

Save the function as a python script. Import the function and run it on this new set of lists


```
list1 = ["'GO:0030955'","GO:0031403", "GO:0031411"]
list2 = ["GO:0031402","GO:0030955"]
list3 = ["GO:0031402", "GO:0030957", "GO:0030955"]

```

```{python,echo=toMessage, eval=F}

import myset_script

myset_script.SetMaker(list1, list2, list3)

```

