---
title: "My Exercise 1"
author: "Rockefeller University, Bioinformatics Resource Centre"
date: "https://rockefelleruniversity.github.io/Intro_To_Python/"
output: 
  html_document:
    number_sections: false  ## if you want number sections at each table header
    theme: united  # many options for theme, this one is my favorite.
    highlight: tango  # specifies the syntax highlighting style
params:
  toMessage: false    
---

```{r, setup,include=FALSE}
toMessage <- ifelse(!is.null(params$toMessage), params$toMessage, FALSE)
message(toMessage)
```


<p>&nbsp;</p>
These exercises are about data types and custom functions from Session 1 [session1](https://rockefelleruniversity.github.io/Intro_To_Python/). 


**Exercise 1** - **Functions**

- Look up what the `pow()` function does and how it works.

```{python, echo=toMessage}
help(pow)

```

- Use the `pow()` function to calculate 4^13.3

```{python, echo=toMessage}
pow(4,13.3)

```

- What data type is 4^13.3? Coerce it into an integer. Then a string. 

```{python,echo=toMessage}
myfloat = pow(4,13.3)
type(myfloat)

```

```{python,echo=toMessage}
myint = int(myfloat)
type(myint)

```

```{python,echo=toMessage}
mystr = int(myint)
mystr
type(mystr)

```

**Exercise 2** - **Variables**

- Create a variable named "myfirst_var" and store a number in it.
- Print the variable with the print() statement

```{python, echo=toMessage}

myfirst_var = 1

print(myfirst_var)


```

- Now let's do a mathematical operation within a variable called "operation_var"; let's try 2+2. Print the result.
    
```{python, echo=toMessage}


operation_var = 2+2

print(operation_var)



```

- Notice how you can perform math operations within a variable. 
    
- Now let's create a third variable. Start the name of the variable with a number, followed by an underscore and the word "var". Store a random number in it.  

```{python, echo=toMessage, eval=F}

1_var = 1

print(1_var)

```


```{python, eval=T, echo=F}
# try:
#   1_var = 1
# except Exception as e:
#   print(e)
  
print('  File "<string>", line 1\n    1_var = 1\n     ^\nSyntaxError: invalid decimal literal\n  File "<string>", line 1\n    print(1_var)\n           ^\nSyntaxError: invalid decimal literal')
```




- Notice how you obtain a syntax error? Now let's try this again: create a new variable, this time starting with the word "var", underscore, and a number. Store a random number in it and print your variable. 
 
```{python, echo=toMessage}
var_1 = 1

print(var_1)
```


- This naming convention is acceptable. Now create a different variable containing symbols (e.g. @&%^). Store a random number in it. 
    
```{python, echo=toMessage, eval=F}

var_% = 1

print(var_%)

```

```{python, eval=T, echo=F}
# try:
#   1_var = 1
# except Exception as e:
#   print(e)
  
print('  File "<string>", line 1\n    var_% = 1\n     ^\nSyntaxError: invalid decimal literal\n  File "<string>", line 1\n    print(var_%)\n               ^\nSyntaxError: invalid syntax')
```


-  Once more, notice how you obtain a syntax error. Symbols are not accepted when naming a variable.


**Exercise 3** - **Coercion**

- Now let's create a variable called "coerce_var" and store the word "hello" in it. 
- Check the type of coerce_var with type()
- Let's try coercing it into a numeric integer with int(). What happens if you do this?
    
    
```{python, echo=toMessage, eval=F}

coerce_var = "hello"

type(coerce_var)

int(coerce_var)
```

```{python, eval=T, echo=F}

coerce_var = "hello"
type(coerce_var)
try:
  int(coerce_var)
except Exception as e:
  print(e)
  
```

- Notice how you get an error when attempting this; you cannot convert "hello" into an integer. Let's try converting coerce_var into a bool() now
    
```{python, echo=toMessage}

bool(coerce_var)

```

- coerce_var has been converted to a boolean type variable.
- Therefore, you can convert strings of characters into boolean types but not numeric types. 
- Let's try vice versa: create a variable called "coerce_num" and store a number in it. Coerce it into a string with str()
    
```{python, echo=toMessage}

coerce_num = 3

str(coerce_num)
```

- Notice how there is no error this time. It is possible to coerce a numeric type into a string.
- Let's try storing a number as a string (i.e. with quotations), and changing its type to integer.

```{python, echo=toMessage}    
coerce_var = "3"

type(coerce_var)

int(coerce_var)
    
type(int(coerce_var))

```

- This is possible given that numeric characters do have an integer equivalent.
    
**Exercise 4** - **Concatenation**

- From the methods learned in class, try concatenating the strings "I" " code" in 3 different ways. First try to concatenate both strings within one variable. Print the results from your different attempts.

    
```{python, echo=toMessage}

concatenated_str = "I" " code"

print(concatenated_str)


concatenated_str = "I" + " code"

print(concatenated_str)

concatenated_str = "I"
concatenated_str += " code"

print(concatenated_str)

```


- Then try creating 1 variable called "concatenate_1" which stores "I" and another called "concatenate_2" which stores " code" and concatenate both variables. Try, for example, print(concatentate_1 + concatenate_2) - what do you get?
    
```{python, echo=toMessage}

concatenate_1 = "I"
concatenate_2 = " code"

print(concatenate_1 + concatenate_2)



```

**Exercise 5** - **Lists**

- Create a list containing the values 1,2,3,4,5.

```{python,echo=toMessage}
[1,2,3,4,5]

```
- Create a list containing the values a,b,c,d,e, but assign it to a new variable called `x`.

```{python,echo=toMessage}
x = ["a","b","c","d","e"]
x
```

- Create a list containing the values a,b,c, repeated 5 times and assign it to a new variable

```{python,echo=toMessage}
y = ["a","b","c"] * 5
y
```

- Create a sublist with indexing. Use the variable you just created and extract the the 10th through to 15th position.

```{python, echo=toMessage}
y[9:14]
```

- With the same variable, let's use "-" indexing to get the last value of our list.
    
```{python, echo=toMessage}

y[-1]


```

- Now print the values from [0:-1]
    
```{python, echo=toMessage}

y[0:-1]


```

- Notice how the last value of your list is missing, even though you access it with [-1]. That's because slicing is exclusive, while indexing is inclusive. 
    

- Append the list in variable x. Add the string z.
```{python, echo=toMessage}
x.append('z')
x
```

- Delete the 2nd through 6th entry of x.
```{python, echo=toMessage}
del(x[1:5])
x
```

- Lets go back to variable y. Sort it in reverse order.
```{python, echo=toMessage}
y.sort(reverse=True)
y
```

  
- Multiply the y variable by 2. 
    
```{python, echo=toMessage}

y * 2



```
    

- Use the function .remove() to eliminate "a" from your list.
    
```{python, echo=toMessage}

y.remove("a")

print(y)

```

- Notice that .remove() eliminates only the first instance of your specified entry.
   
- Create a list of lists. Use the values 1,2,3,4,5, along with the lists x and y. 

```{python, echo=toMessage}
nested_list = [[1,2,3,4,5], x, y]
nested_list
```

- Take your previous list of lists and use indexing to find the third entry of your third list.

```{python, echo=toMessage}

nested_list[2][2]

```

**Exercise 3** - **Tuples**

- Create a tuple containing the values 1,2,3,4,5.

```{python,echo=toMessage}
(1,2,3,4,5)

```


- Coerce list in variable x into a tuple.

```{python,echo=toMessage}
tuple(x)

```


- Make a touple with your list of lists.
- Print your results
    
```{python, echo=toMessage}

nested_list_tuple = tuple(nested_list)

print(nested_list_tuple)

```



**Exercise 4** - **Dictionaries**

- Create a dictionary containing a list of floats, a list of integers and a tuple of strings.

```{python,echo=toMessage}

my_dict = {
    'my_float_list': [1.5,2.5,3.5],
    'my_integer_list': [4,5,6],
    'my_strings_tuple': ("a","b","c")
}
my_dict

```

- Create a dictionary containing GO terms and their corresponding genes:

* GO:0030955 - PKM, ADPRH, ATP4A, DRG1
* GO:0031403 - IMPA1, PDXK
* GO:0031402 - SLC6A4, CAPN3, TDG, ATP1A2

```{python,echo=toMessage}

my_dict = {
    'GO:0030955': ["PKM", "ADPRH", "ATP4A", "DRG1"],
    'GO:0031403': ["IMPA1", "PDXK"],
    'GO:0031402': ["SLC6A4", "CAPN3", "TDG", "ATP1A2"]
}
my_dict

```

- Add a new parental GO term: GO:0031420. This contains all the genes from the other 3 entries.  

```{python,echo=toMessage}

my_dict = {
    'GO:0030955': ["PKM", "ADPRH", "ATP4A", "DRG1"],
    'GO:0031403': ["IMPA1", "PDXK"],
    'GO:0031402': ["SLC6A4", "CAPN3", "TDG", "ATP1A2"]
}
my_dict.setdefault('GO:0031420', my_dict['GO:0030955'] + my_dict['GO:0031403'] + my_dict['GO:0031402'])
my_dict
```

**Exercise 5** - **Sets**

- Create 2 sets of gene names: 
  - PKM, ADPRH, ZNF724,ATP4A,GSS, DRG1, FA2H, MCM10
  - SLC6A4, MCM10, CAPN3, TDG, ATP1A2,GSS, BRCA1, HIVEP2, PKM

```{python,echo=toMessage}

my_set1 = {"PKM", "ADPRH", "ZNF724","ATP4A","GSS", "DRG1", "FA2H", "MCM10"}
my_set2 = {"SLC6A4", "MCM10", "CAPN3", "TDG", "ATP1A2","GSS", "BRCA1", "HIVEP2", "PKM"}

```

- These are genes of interest from two experiments. What genes overlap between the two?

```{python,echo=toMessage}

my_set1.intersection(my_set2) 

```


**Exercise 5** - **NumPy**

- Import NumPy

```{python,echo=toMessage}

import numpy as np

```

- Create a NumPy array with 4 columns and 5 rows.

* Sample - R1, R2, R3, R4, R5
* Year - 1990, 2010, 2005, 2015, 2012
* Replicate - True, True, False, False, False
* Tissue - Skin, Skin, Brain, Brain, Brain

```{python,echo=toMessage}

arr_2d = np.array([["R1", 1990, True, "Skin"],
  ["R2", 2010, True, "Skin"], 
  ["R3", 2005, False, "Brain"],
  ["R4", 2015, False, "Brain"],
  ["R5", 2012, False, "Brain"]])
arr_2d

```

- Slice the array to get just the Sample and Year.

```{python,echo=toMessage}

arr_2d[:,0:2]

```

- Subset the array to just Brain Tissue samples. 

```{python,echo=toMessage}

arr_2d[arr_2d[:,3] =="Brain",:]

```

**Exercise 6** - **Custom Functions**

- Create a function which takes one number and returns the square of that number

```{python,echo=toMessage}

def squareOfNumber(number):
  squareNumber = number*number
  return squareNumber

squareOfNumber(9)

```

- Create a function which takes two numbers and returns the mean and the minimum

```{python,echo=toMessage}

def mean_and_minOfNumbers(number1, number2):
  meanNumber = (number1 + number2) /2
  minNumber = min([number1, number2])
  return [meanNumber,minNumber]

mean_and_minOfNumbers(1,3)
```


